### ISSUE TITLE
cant restore to ios 4

### ISSUE THREAD

**Issue by Savefade** [LukeZGD/iPhone4Down#4]
i tried restoring my iphone 4 to ios 4.3.5 but the program said i coudnt find the serial number. How do i fix it.

**Comment by LukeZGD** [comment]
iOS 4 support is not something I would be able to fix, srry.. (my device doesnt seem to support it so I cant test)

Terminal logs might help, but I don't think I can do much

Try using cherryflowerJB instead, it fully supports restores to iOS 4.3.5

**Comment by Savefade** [comment]
> 
> 
> iOS 4 support is not something I would be able to fix, srry.. (my device doesnt seem to support it so I cant test)
> 
> Terminal logs might help, but I don't think I can do much
> 
> Try using cherryflowerJB instead, it fully supports restores to iOS 4.3.5

i dont have a mac. I dont think cherryflowerJB works on ubuntu

**Comment by Savefade** [comment]
> 
> 
> iOS 4 support is not something I would be able to fix, srry.. (my device doesnt seem to support it so I cant test)
> 
> Terminal logs might help, but I don't think I can do much
> 
> Try using cherryflowerJB instead, it fully supports restores to iOS 4.3.5

You can try first to restore to ios 7.1.2 and then try 4.3.5

**Comment by LukeZGD** [comment]
> You can try first to restore to ios 7.1.2 and then try 4.3.5

Yeah I already tried multiple ways, my phone just doesn't support it, it won't boot at all

Your device might also be incompatible also, check the manufacturing date using the serial number

In any case, I can't (and do not have plans to) fix iOS 4 restores in iPhone4Down
