### ISSUE TITLE
Why isn't ios 4 support ever possible

### ISSUE THREAD

**Issue by theIdeviceguy18383** [LukeZGD/iPhone4Down#6]
If I try to install ios 4 on my iPhone 4 it gets stuck in llb/ibss fake dfu mode, it was manufactured in 2/7/2011 so it should run ios 4 without a problem

**Comment by LukeZGD** [comment]
idk

**Comment by LukeZGD** [comment]
see my comment [here](https://github.com/LukeZGD/iPhone4Down/issues/4#issuecomment-841820124)
