### ISSUE TITLE
Support for 6.1.3 on iPhone3,3

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iPhone4Down#7]
Hello, dora2ios recently released a new tool that supports iPhone3,3 (iPhone 4 CDMA). Can you add support using the iPhone3,3 bundle on the new tool?

Link: https://dora2ios.web.app/konayuki/index.html

**Comment by LukeZGD** [comment]
Updated the readme regarding iPhone3,3 support. iPhone4Down will not and cannot be updated for iPhone3,3 support. iPhone4Down ultimately just uses the only Linux build of ch3rryflower. Look forward to updates for powdersn0w instead. If powdersn0w gets updated with Linux support, then iPhone4Down will no longer be needed
